spring:
  profiles:
    active: development
---

spring:
  profiles: development
  application:
    name: auth-service
server:
  port: 9191
  contextPath: /uaa

logging.level.org.springframework.security: DEBUG


---

spring:
  profiles: test
  datasource:
      url: jdbc:mysql://localhost:3306/db_auth?useSSL=false&requireSSL=false
      username: root
      password: dbpass
      initialize: true
  application:
    name: auth-service
server:
  port: 9191